server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/hindu?useSSL=false
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE